.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching sqrtf, 0x8

glabel sqrtf
    /* 372E0 800366E0 03E00008 */  jr         $ra
    /* 372E4 800366E4 46006004 */   sqrt.s    $f0, $f12
endlabel sqrtf
    /* 372E8 800366E8 00000000 */  nop
    /* 372EC 800366EC 00000000 */  nop
