.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching _bcopy, 0x304

glabel _bcopy
    /* 3D560 8003C960 10C0001A */  beqz       $a2, .L8003C9CC
    /* 3D564 8003C964 00A03825 */   or        $a3, $a1, $zero
    /* 3D568 8003C968 10850018 */  beq        $a0, $a1, .L8003C9CC
    /* 3D56C 8003C96C 00A4082A */   slt       $at, $a1, $a0
    /* 3D570 8003C970 54200008 */  bnel       $at, $zero, .L8003C994
    /* 3D574 8003C974 28C10010 */   slti      $at, $a2, 0x10
    /* 3D578 8003C978 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* 3D57C 8003C97C 00A2082A */  slt        $at, $a1, $v0
    /* 3D580 8003C980 50200004 */  beql       $at, $zero, .L8003C994
    /* 3D584 8003C984 28C10010 */   slti      $at, $a2, 0x10
    /* 3D588 8003C988 1000005B */  b          .L8003CAF8
    /* 3D58C 8003C98C 28C10010 */   slti      $at, $a2, 0x10
    /* 3D590 8003C990 28C10010 */  slti       $at, $a2, 0x10
  .L8003C994:
    /* 3D594 8003C994 14200005 */  bnez       $at, .L8003C9AC
    /* 3D598 8003C998 00000000 */   nop
    /* 3D59C 8003C99C 30820003 */  andi       $v0, $a0, 0x3
    /* 3D5A0 8003C9A0 30A30003 */  andi       $v1, $a1, 0x3
    /* 3D5A4 8003C9A4 1043000B */  beq        $v0, $v1, .L8003C9D4
    /* 3D5A8 8003C9A8 00000000 */   nop
  .L8003C9AC:
    /* 3D5AC 8003C9AC 10C00007 */  beqz       $a2, .L8003C9CC
    /* 3D5B0 8003C9B0 00000000 */   nop
    /* 3D5B4 8003C9B4 00861821 */  addu       $v1, $a0, $a2
  .L8003C9B8:
    /* 3D5B8 8003C9B8 80820000 */  lb         $v0, 0x0($a0)
    /* 3D5BC 8003C9BC 24840001 */  addiu      $a0, $a0, 0x1
    /* 3D5C0 8003C9C0 24A50001 */  addiu      $a1, $a1, 0x1
    /* 3D5C4 8003C9C4 1483FFFC */  bne        $a0, $v1, .L8003C9B8
    /* 3D5C8 8003C9C8 A0A2FFFF */   sb        $v0, -0x1($a1)
  .L8003C9CC:
    /* 3D5CC 8003C9CC 03E00008 */  jr         $ra
    /* 3D5D0 8003C9D0 00E01025 */   or        $v0, $a3, $zero
  .L8003C9D4:
    /* 3D5D4 8003C9D4 10400018 */  beqz       $v0, .L8003CA38
    /* 3D5D8 8003C9D8 24010001 */   addiu     $at, $zero, 0x1
    /* 3D5DC 8003C9DC 1041000F */  beq        $v0, $at, .L8003CA1C
    /* 3D5E0 8003C9E0 24010002 */   addiu     $at, $zero, 0x2
    /* 3D5E4 8003C9E4 50410008 */  beql       $v0, $at, .L8003CA08
    /* 3D5E8 8003C9E8 84820000 */   lh        $v0, 0x0($a0)
    /* 3D5EC 8003C9EC 80820000 */  lb         $v0, 0x0($a0)
    /* 3D5F0 8003C9F0 24840001 */  addiu      $a0, $a0, 0x1
    /* 3D5F4 8003C9F4 24A50001 */  addiu      $a1, $a1, 0x1
    /* 3D5F8 8003C9F8 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 3D5FC 8003C9FC 1000000E */  b          .L8003CA38
    /* 3D600 8003CA00 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* 3D604 8003CA04 84820000 */  lh         $v0, 0x0($a0)
  .L8003CA08:
    /* 3D608 8003CA08 24840002 */  addiu      $a0, $a0, 0x2
    /* 3D60C 8003CA0C 24A50002 */  addiu      $a1, $a1, 0x2
    /* 3D610 8003CA10 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 3D614 8003CA14 10000008 */  b          .L8003CA38
    /* 3D618 8003CA18 A4A2FFFE */   sh        $v0, -0x2($a1)
  .L8003CA1C:
    /* 3D61C 8003CA1C 80820000 */  lb         $v0, 0x0($a0)
    /* 3D620 8003CA20 84830001 */  lh         $v1, 0x1($a0)
    /* 3D624 8003CA24 24840003 */  addiu      $a0, $a0, 0x3
    /* 3D628 8003CA28 24A50003 */  addiu      $a1, $a1, 0x3
    /* 3D62C 8003CA2C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 3D630 8003CA30 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* 3D634 8003CA34 A4A3FFFE */  sh         $v1, -0x2($a1)
  .L8003CA38:
    /* 3D638 8003CA38 28C10020 */  slti       $at, $a2, 0x20
    /* 3D63C 8003CA3C 54200016 */  bnel       $at, $zero, .L8003CA98
    /* 3D640 8003CA40 28C10010 */   slti      $at, $a2, 0x10
    /* 3D644 8003CA44 8C820000 */  lw         $v0, 0x0($a0)
    /* 3D648 8003CA48 8C830004 */  lw         $v1, 0x4($a0)
    /* 3D64C 8003CA4C 8C880008 */  lw         $t0, 0x8($a0)
    /* 3D650 8003CA50 8C89000C */  lw         $t1, 0xC($a0)
    /* 3D654 8003CA54 8C8A0010 */  lw         $t2, 0x10($a0)
    /* 3D658 8003CA58 8C8B0014 */  lw         $t3, 0x14($a0)
    /* 3D65C 8003CA5C 8C8C0018 */  lw         $t4, 0x18($a0)
    /* 3D660 8003CA60 8C8D001C */  lw         $t5, 0x1C($a0)
    /* 3D664 8003CA64 24840020 */  addiu      $a0, $a0, 0x20
    /* 3D668 8003CA68 24A50020 */  addiu      $a1, $a1, 0x20
    /* 3D66C 8003CA6C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 3D670 8003CA70 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* 3D674 8003CA74 ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* 3D678 8003CA78 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* 3D67C 8003CA7C ACA9FFEC */  sw         $t1, -0x14($a1)
    /* 3D680 8003CA80 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* 3D684 8003CA84 ACABFFF4 */  sw         $t3, -0xC($a1)
    /* 3D688 8003CA88 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* 3D68C 8003CA8C 1000FFEA */  b          .L8003CA38
    /* 3D690 8003CA90 ACADFFFC */   sw        $t5, -0x4($a1)
  .L8003CA94:
    /* 3D694 8003CA94 28C10010 */  slti       $at, $a2, 0x10
  .L8003CA98:
    /* 3D698 8003CA98 5420000E */  bnel       $at, $zero, .L8003CAD4
    /* 3D69C 8003CA9C 28C10004 */   slti      $at, $a2, 0x4
    /* 3D6A0 8003CAA0 8C820000 */  lw         $v0, 0x0($a0)
    /* 3D6A4 8003CAA4 8C830004 */  lw         $v1, 0x4($a0)
    /* 3D6A8 8003CAA8 8C880008 */  lw         $t0, 0x8($a0)
    /* 3D6AC 8003CAAC 8C89000C */  lw         $t1, 0xC($a0)
    /* 3D6B0 8003CAB0 24840010 */  addiu      $a0, $a0, 0x10
    /* 3D6B4 8003CAB4 24A50010 */  addiu      $a1, $a1, 0x10
    /* 3D6B8 8003CAB8 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 3D6BC 8003CABC ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* 3D6C0 8003CAC0 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* 3D6C4 8003CAC4 ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* 3D6C8 8003CAC8 1000FFF2 */  b          .L8003CA94
    /* 3D6CC 8003CACC ACA9FFFC */   sw        $t1, -0x4($a1)
  .L8003CAD0:
    /* 3D6D0 8003CAD0 28C10004 */  slti       $at, $a2, 0x4
  .L8003CAD4:
    /* 3D6D4 8003CAD4 1420FFB5 */  bnez       $at, .L8003C9AC
    /* 3D6D8 8003CAD8 00000000 */   nop
    /* 3D6DC 8003CADC 8C820000 */  lw         $v0, 0x0($a0)
    /* 3D6E0 8003CAE0 24840004 */  addiu      $a0, $a0, 0x4
    /* 3D6E4 8003CAE4 24A50004 */  addiu      $a1, $a1, 0x4
    /* 3D6E8 8003CAE8 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 3D6EC 8003CAEC 1000FFF8 */  b          .L8003CAD0
    /* 3D6F0 8003CAF0 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* 3D6F4 8003CAF4 28C10010 */  slti       $at, $a2, 0x10
  .L8003CAF8:
    /* 3D6F8 8003CAF8 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* 3D6FC 8003CAFC 14200005 */  bnez       $at, .L8003CB14
    /* 3D700 8003CB00 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* 3D704 8003CB04 30820003 */  andi       $v0, $a0, 0x3
    /* 3D708 8003CB08 30A30003 */  andi       $v1, $a1, 0x3
    /* 3D70C 8003CB0C 1043000D */  beq        $v0, $v1, .L8003CB44
    /* 3D710 8003CB10 00000000 */   nop
  .L8003CB14:
    /* 3D714 8003CB14 10C0FFAD */  beqz       $a2, .L8003C9CC
    /* 3D718 8003CB18 00000000 */   nop
    /* 3D71C 8003CB1C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 3D720 8003CB20 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 3D724 8003CB24 00861823 */  subu       $v1, $a0, $a2
  .L8003CB28:
    /* 3D728 8003CB28 80820000 */  lb         $v0, 0x0($a0)
    /* 3D72C 8003CB2C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 3D730 8003CB30 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 3D734 8003CB34 1483FFFC */  bne        $a0, $v1, .L8003CB28
    /* 3D738 8003CB38 A0A20001 */   sb        $v0, 0x1($a1)
    /* 3D73C 8003CB3C 03E00008 */  jr         $ra
    /* 3D740 8003CB40 00E01025 */   or        $v0, $a3, $zero
  .L8003CB44:
    /* 3D744 8003CB44 10400018 */  beqz       $v0, .L8003CBA8
    /* 3D748 8003CB48 24010003 */   addiu     $at, $zero, 0x3
    /* 3D74C 8003CB4C 1041000F */  beq        $v0, $at, .L8003CB8C
    /* 3D750 8003CB50 24010002 */   addiu     $at, $zero, 0x2
    /* 3D754 8003CB54 50410008 */  beql       $v0, $at, .L8003CB78
    /* 3D758 8003CB58 8482FFFE */   lh        $v0, -0x2($a0)
    /* 3D75C 8003CB5C 8082FFFF */  lb         $v0, -0x1($a0)
    /* 3D760 8003CB60 2484FFFF */  addiu      $a0, $a0, -0x1
    /* 3D764 8003CB64 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* 3D768 8003CB68 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* 3D76C 8003CB6C 1000000E */  b          .L8003CBA8
    /* 3D770 8003CB70 A0A20000 */   sb        $v0, 0x0($a1)
    /* 3D774 8003CB74 8482FFFE */  lh         $v0, -0x2($a0)
  .L8003CB78:
    /* 3D778 8003CB78 2484FFFE */  addiu      $a0, $a0, -0x2
    /* 3D77C 8003CB7C 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* 3D780 8003CB80 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* 3D784 8003CB84 10000008 */  b          .L8003CBA8
    /* 3D788 8003CB88 A4A20000 */   sh        $v0, 0x0($a1)
  .L8003CB8C:
    /* 3D78C 8003CB8C 8082FFFF */  lb         $v0, -0x1($a0)
    /* 3D790 8003CB90 8483FFFD */  lh         $v1, -0x3($a0)
    /* 3D794 8003CB94 2484FFFD */  addiu      $a0, $a0, -0x3
    /* 3D798 8003CB98 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* 3D79C 8003CB9C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* 3D7A0 8003CBA0 A0A20002 */  sb         $v0, 0x2($a1)
    /* 3D7A4 8003CBA4 A4A30000 */  sh         $v1, 0x0($a1)
  .L8003CBA8:
    /* 3D7A8 8003CBA8 28C10020 */  slti       $at, $a2, 0x20
    /* 3D7AC 8003CBAC 54200016 */  bnel       $at, $zero, .L8003CC08
    /* 3D7B0 8003CBB0 28C10010 */   slti      $at, $a2, 0x10
    /* 3D7B4 8003CBB4 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 3D7B8 8003CBB8 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 3D7BC 8003CBBC 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 3D7C0 8003CBC0 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 3D7C4 8003CBC4 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* 3D7C8 8003CBC8 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* 3D7CC 8003CBCC 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* 3D7D0 8003CBD0 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* 3D7D4 8003CBD4 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* 3D7D8 8003CBD8 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* 3D7DC 8003CBDC 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* 3D7E0 8003CBE0 ACA2001C */  sw         $v0, 0x1C($a1)
    /* 3D7E4 8003CBE4 ACA30018 */  sw         $v1, 0x18($a1)
    /* 3D7E8 8003CBE8 ACA80014 */  sw         $t0, 0x14($a1)
    /* 3D7EC 8003CBEC ACA90010 */  sw         $t1, 0x10($a1)
    /* 3D7F0 8003CBF0 ACAA000C */  sw         $t2, 0xC($a1)
    /* 3D7F4 8003CBF4 ACAB0008 */  sw         $t3, 0x8($a1)
    /* 3D7F8 8003CBF8 ACAC0004 */  sw         $t4, 0x4($a1)
    /* 3D7FC 8003CBFC 1000FFEA */  b          .L8003CBA8
    /* 3D800 8003CC00 ACAD0000 */   sw        $t5, 0x0($a1)
  .L8003CC04:
    /* 3D804 8003CC04 28C10010 */  slti       $at, $a2, 0x10
  .L8003CC08:
    /* 3D808 8003CC08 5420000E */  bnel       $at, $zero, .L8003CC44
    /* 3D80C 8003CC0C 28C10004 */   slti      $at, $a2, 0x4
    /* 3D810 8003CC10 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 3D814 8003CC14 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* 3D818 8003CC18 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* 3D81C 8003CC1C 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* 3D820 8003CC20 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* 3D824 8003CC24 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* 3D828 8003CC28 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* 3D82C 8003CC2C ACA2000C */  sw         $v0, 0xC($a1)
    /* 3D830 8003CC30 ACA30008 */  sw         $v1, 0x8($a1)
    /* 3D834 8003CC34 ACA80004 */  sw         $t0, 0x4($a1)
    /* 3D838 8003CC38 1000FFF2 */  b          .L8003CC04
    /* 3D83C 8003CC3C ACA90000 */   sw        $t1, 0x0($a1)
  .L8003CC40:
    /* 3D840 8003CC40 28C10004 */  slti       $at, $a2, 0x4
  .L8003CC44:
    /* 3D844 8003CC44 1420FFB3 */  bnez       $at, .L8003CB14
    /* 3D848 8003CC48 00000000 */   nop
    /* 3D84C 8003CC4C 8C82FFFC */  lw         $v0, -0x4($a0)
    /* 3D850 8003CC50 2484FFFC */  addiu      $a0, $a0, -0x4
    /* 3D854 8003CC54 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* 3D858 8003CC58 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* 3D85C 8003CC5C 1000FFF8 */  b          .L8003CC40
    /* 3D860 8003CC60 ACA20000 */   sw        $v0, 0x0($a1)
endlabel _bcopy
    /* 3D864 8003CC64 00000000 */  nop
    /* 3D868 8003CC68 00000000 */  nop
    /* 3D86C 8003CC6C 00000000 */  nop
