.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching _bzero, 0x9C

glabel _bzero
    /* 3BF80 8003B380 28A1000C */  slti       $at, $a1, 0xC
    /* 3BF84 8003B384 1420001D */  bnez       $at, .L8003B3FC
    /* 3BF88 8003B388 00041823 */   negu      $v1, $a0
    /* 3BF8C 8003B38C 30630003 */  andi       $v1, $v1, 0x3
    /* 3BF90 8003B390 10600003 */  beqz       $v1, .L8003B3A0
    /* 3BF94 8003B394 00A32823 */   subu      $a1, $a1, $v1
    /* 3BF98 8003B398 A8800000 */  swl        $zero, 0x0($a0)
    /* 3BF9C 8003B39C 00832021 */  addu       $a0, $a0, $v1
  .L8003B3A0:
    /* 3BFA0 8003B3A0 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 3BFA4 8003B3A4 00A13824 */  and        $a3, $a1, $at
    /* 3BFA8 8003B3A8 10E0000C */  beqz       $a3, .L8003B3DC
    /* 3BFAC 8003B3AC 00A72823 */   subu      $a1, $a1, $a3
    /* 3BFB0 8003B3B0 00E43821 */  addu       $a3, $a3, $a0
  .L8003B3B4:
    /* 3BFB4 8003B3B4 24840020 */  addiu      $a0, $a0, 0x20
    /* 3BFB8 8003B3B8 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* 3BFBC 8003B3BC AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* 3BFC0 8003B3C0 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* 3BFC4 8003B3C4 AC80FFEC */  sw         $zero, -0x14($a0)
    /* 3BFC8 8003B3C8 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 3BFCC 8003B3CC AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 3BFD0 8003B3D0 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 3BFD4 8003B3D4 1487FFF7 */  bne        $a0, $a3, .L8003B3B4
    /* 3BFD8 8003B3D8 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8003B3DC:
    /* 3BFDC 8003B3DC 2401FFFC */  addiu      $at, $zero, -0x4
    /* 3BFE0 8003B3E0 00A13824 */  and        $a3, $a1, $at
    /* 3BFE4 8003B3E4 10E00005 */  beqz       $a3, .L8003B3FC
    /* 3BFE8 8003B3E8 00A72823 */   subu      $a1, $a1, $a3
    /* 3BFEC 8003B3EC 00E43821 */  addu       $a3, $a3, $a0
  .L8003B3F0:
    /* 3BFF0 8003B3F0 24840004 */  addiu      $a0, $a0, 0x4
    /* 3BFF4 8003B3F4 1487FFFE */  bne        $a0, $a3, .L8003B3F0
    /* 3BFF8 8003B3F8 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8003B3FC:
    /* 3BFFC 8003B3FC 18A00005 */  blez       $a1, .L8003B414
    /* 3C000 8003B400 00000000 */   nop
    /* 3C004 8003B404 00A42821 */  addu       $a1, $a1, $a0
  .L8003B408:
    /* 3C008 8003B408 24840001 */  addiu      $a0, $a0, 0x1
    /* 3C00C 8003B40C 1485FFFE */  bne        $a0, $a1, .L8003B408
    /* 3C010 8003B410 A080FFFF */   sb        $zero, -0x1($a0)
  .L8003B414:
    /* 3C014 8003B414 03E00008 */  jr         $ra
    /* 3C018 8003B418 00000000 */   nop
endlabel _bzero
    /* 3C01C 8003B41C 00000000 */  nop
