#ifndef _BMHERO_MAP_IDS_
#define _BMHERO_MAP_IDS_

#define MAP_BOMBER_BASE_ENTRANCE        0
#define MAP_BOMBER_BASE_ELEVATOR        1
#define MAP_BATTLE_ROOM                 2
#define MAP_HYPER_ROOM                  3
#define MAP_HEAVY_ROOM                  4
#define MAP_SKY_ROOM                    5
#define MAP_SECRET_ROOM                 6
#define MAP_BOMBER_BASE_HUB             7 // cutscene map
#define MAP_EMERALD_TUBE                8
#define MAP_BLUE_CAVE                   9
#define MAP_HOLE_LAKE                   10
#define MAP_RED_CAVE                    11
#define MAP_DARK_WOOD                   12
#define MAP_BIG_CANNON                  13
#define MAP_DRAGON_ROAD                 14
#define MAP_NITROS_1                    15
#define MAP_CLOWN_VALLEY                16
#define MAP_GREAT_ROCK                  17
#define MAP_FOG_ROUTE                   18
#define MAP_ENDOL_1                     19
#define MAP_CUTSCENE_UNK14              20
#define MAP_GROOG_HILLS                 21
#define MAP_BUBBLE_HOLE                 22
#define MAP_ERARS_LAKE_1                23
#define MAP_WATERWAY                    24
#define MAP_WATERSLIDER                 25
#define MAP_CUTSCENE_UNK1A              26
#define MAP_WATERPOOL                   27
#define MAP_ROCKIN_ROAD                 28
#define MAP_DARK_PRISON                 29
#define MAP_WARP_ROOM                   30
#define MAP_MILLIAN_ROAD                31
#define MAP_CUTSCENE_UNK20              32
#define MAP_KILLER_GATE                 33
#define MAP_SPIRAL_TOWER                34
#define MAP_SNAKE_ROUTE                 35
#define MAP_BARUDA_CUTSCENE             36
#define MAP_BARUDA                      37
#define MAP_HADES_CRATER_CUTSCENE       38
#define MAP_HADES_CRATER                39
#define MAP_MAGMA_LAKE                  40
#define MAP_MAGMA_DAM                   41
#define MAP_CRYSTA_HOLE                 42
#define MAP_SECRET_LEVEL_1              43
#define MAP_CUTSCENE_UNK2C              44
#define MAP_DEATH_TEMPLE                45
#define MAP_DEATH_ROAD_2                46
#define MAP_DEATH_GARDEN                47
#define MAP_DEATH_ROAD_1                48
#define MAP_FLOAT_ZONE                  49
#define MAP_AQUA_TANK                   50
#define MAP_AQUAWAY                     51
#define MAP_CUTSCENE_UNK34              52
#define MAP_HARD_COASTER                53
#define MAP_DARK_MAZE                   54
#define MAP_MAD_COASTER                 55
#define MAP_MOVE_STONE                  56
#define MAP_BOLBAN_1                    57
#define MAP_CUTSCENE_UNK3A              58
#define MAP_FREEZE_LAKE                 59
#define MAP_JUN_FALLS                   60
#define MAP_HOPPER_LAND                 61
#define MAP_COOL_CAVE                   62
#define MAP_SNOWLAND_CUTSCENE           63
#define MAP_SNOWLAND                    64
#define MAP_STORM_VALLEY                65
#define MAP_EYE_SNAKE                   66
#define MAP_HEAVEN_SKY                  67
#define MAP_AIR_ROOM_SELECT             68
#define MAP_AIR_ROOM                    69
#define MAP_ZERO_G_ROOM                 70
#define MAP_MIRROR_ROOM                 71
#define MAP_NITROS_4_AFTER_CUTSCENE     72
#define MAP_SECRET_LEVEL_2              73
#define MAP_SNOW_CIRCUIT                74
#define MAP_CUTSCENE_UNK4B              75
#define MAP_ENDOL_2                     76
#define MAP_BARUDA_2                    77
#define MAP_CRONUS                      78
#define MAP_NITROS_5                    79
#define MAP_BOLBAN_2                    80
#define MAP_NATIA_2                     81
#define MAP_BAGULAR                     82
#define MAP_BAGULAR_PHASE_3             83
#define MAP_SECRET_LEVEL_3              84
#define MAP_EVIL_BOMBER                 85
#define MAP_CUTSCENE_UNK56              86
#define MAP_NITROS_2                    87
#define MAP_NITROS_3                    88
#define MAP_NITROS_4                    89
#define MAP_NATIA_1                     90
#define MAP_CUTSCENE_UNK5B              91
#define MAP_AQUAWAY_IN_FISH             92
#define MAP_ERARS_2                     93
#define MAP_ERARS_3                     94
#define MAP_HEAVEN_SKY_2                95
#define MAP_FLY_TEST_STAGE              96
#define MAP_BONUS_STAGE_97              97
#define MAP_BONUS_STAGE_98              98
#define MAP_BONUS_STAGE_99              99
#define MAP_BONUS_STAGE_100             100
#define MAP_BONUS_UNUSED_STAGE          101
#define MAP_OUTER_ROAD                  102
#define MAP_INNER_ROAD                  103
#define MAP_GROOG_HILLS_2               104
#define MAP_ZERO_G_ENTRANCE             105
#define MAP_MIRROR_ROOM_ENTRANCE        106
#define MAP_NATIA_1_ENTRANCE            107
#define MAP_BAGULAR_PHASE_2             108
#define MAP_SPACE                       109
#define MAP_SNOWMAN_RACE                110
#define MAP_GOLD_BOMBER_HOLE_LAKE       111
#define MAP_GOLD_BOMBER_BIG_CANNON      112
#define MAP_DEBUG_STAGE_UNK71           113
#define MAP_DEBUG_STAGE_UNK72           114
#define MAP_DEBUG_STAGE_UNK73           115
#define MAP_DEBUG_STAGE_UNK74           116
#define MAP_DEBUG_STAGE_UNK75           117
#define MAP_DEBUG_STAGE_UNK76           118
#define MAP_DEBUG_STAGE_UNK77           119
#define MAP_DEBUG_STAGE_UNK78           120
#define MAP_DEBUG_STAGE_UNK79           121
#define MAP_DEBUG_STAGE_UNK7A           122
#define MAP_DEBUG_STAGE_UNK7B           123
#define MAP_DEBUG_STAGE_UNK7C           124
#define MAP_HADES_CRATER_TEST           125
#define MAP_DEBUG_ROOM_EVERY_ITEM       126
#define MAP_DEBUG_ROOM_AGAIN            127

#define MAP_FIRST_CUTSCENE_MAP (MAP_DEBUG_ROOM_AGAIN+1)

#define MAP_CUTSCENE_BOMBER_HUB_ROOM    128
#define MAP_CUTSCENE_BOMBER_AREA_2_1    129
#define MAP_CUTSCENE_BOMBER_AREA_2_2    130
#define MAP_CUTSCENE_NITROS_1           131
#define MAP_CUTSCENE_NITROS_1_WIN       132
#define MAP_CUTSCENE_PRIMUS_AREA_2      133
#define MAP_CUTSCENE_NITROS_2           134
#define MAP_CUTSCENE_NITROS_2_WIN       135
#define MAP_CUTSCENE_BASE_ELEVATOR      136
#define MAP_CUTSCENE_NITROS_3           137
#define MAP_CUTSCENE_ENDOL              138
#define MAP_CUTSCENE_NITROS_3_WIN       139
#define MAP_CUTSCENE_ENDOL_WIN          140
#define MAP_CUTSCENE_BOLBAN_WIN         141
#define MAP_CUTSCENE_KANATIA_AREA_2_2   142
#define MAP_CUTSCENE_BARUDA_WIN         143
#define MAP_CUTSCENE_PRIMUS_AREA_3      144
#define MAP_CUTSCENE_BARUDA             145
#define MAP_CUTSCENE_NITROS_4           146
#define MAP_CUTSCENE_NATIA_WIN          147
#define MAP_CUTSCENE_KANATIA_AREA_2_1   148
#define MAP_CUTSCENE_BOLBAN             149
#define MAP_CUTSCENE_MAZONE_AREA_2      150
#define MAP_CUTSCENE_NATIA              151
#define MAP_CUTSCENE_KANATIA            152
#define MAP_CUTSCENE_AQUA_TANK_FILLING  153
#define MAP_CUTSCENE_NEED_DISKS         154
#define MAP_CUTSCENE_MAZONE             155
#define MAP_CUTSCENE_GARADEN_1          156
#define MAP_CUTSCENE_NITROS_5           157
#define MAP_CUTSCENE_NITROS_5_WIN       158
#define MAP_CUTSCENE_BAGULAR_1          159
#define MAP_CUTSCENE_BAGULAR_2          160
#define MAP_CUTSCENE_BAGULAR_3          161
#define MAP_CUTSCENE_BAGULAR_3_WIN      162
#define MAP_CUTSCENE_GOSSICK            163
#define MAP_CUTSCENE_EVIL_BOMBER        164
#define MAP_CUTSCENE_GARADEN_2          165
#define MAP_CUTSCENE_GROOG_HILLS        166
#define MAP_CUTSCENE_NITROS_5_LOSE      167
#define MAP_CUTSCENE_GROOG_HILLS_WINTER 168
#define MAP_CUTSCENE_POST_AQUA_TANK     169
#define MAP_CUTSCENE_GAME_START         170
#define MAP_CUTSCENE_GOSSICK_APPEARS    171
#define MAP_SLIDER_RACE_START           172
#define MAP_SLIDER_RACE_WIN             173
#define MAP_SLIDER_RACE_LOSE            174
#define MAP_TREASURE_HUNT_HUB_CUTSCENE  175
#define MAP_TREASURE_HUNT_ENDING        176
#define MAP_GOLD_BOMBER_HUB_CUTSCENE    177
#define MAP_GOLD_BOMBER_LEAVING_BASE    178
#define MAP_GOLD_BOMBER_MISSION_DONE    179
#define MAP_GOLD_BOMBER_FINAL_SCORE     180
#define MAP_BOMBER_STAR_HUB_CUTSCENE    181
#define MAP_BOMBER_STAR_LEAVING_BASE    182
#define MAP_BOMBER_STAR_GOING_TO_STAR   183
#define MAP_BOMBER_STAR_LEAVING_STAR    184
#define MAP_BOMBER_STAR_FINAL_SCORE     185
#define MAP_POST_EVIL_BOMBER_CUTSCENE   186
#define MAP_CREDITS                     187
#define MAP_UNKBC                       188 // crashes
#define MAP_UNKBD                       189 // crashes
#define MAP_UNKBE                       190 // crashes
#define MAP_UNKBF                       191 // crashes

#define LAST_MAP  MAP_UNKBF
#define MAP_COUNT LAST_MAP+1 // account for 0

#endif // _BMHERO_MAP_IDS_
