.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osExceptionPreamble, 0x10

glabel __osExceptionPreamble
    /* 3B5B0 8003A9B0 3C1A8004 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 3B5B4 8003A9B4 275AA9C0 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 3B5B8 8003A9B8 03400008 */  jr         $k0
    /* 3B5BC 8003A9BC 00000000 */   nop
endlabel __osExceptionPreamble

/* Handwritten function */
nonmatching __osException, 0x534

glabel __osException
    /* 3B5C0 8003A9C0 3C1A8006 */  lui        $k0, %hi(D_8005A920) /* handwritten instruction */
    /* 3B5C4 8003A9C4 275AA920 */  addiu      $k0, $k0, %lo(D_8005A920) /* handwritten instruction */
    /* 3B5C8 8003A9C8 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 3B5CC 8003A9CC 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 3B5D0 8003A9D0 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3B5D4 8003A9D4 2401FFFC */  addiu      $at, $zero, -0x4
    /* 3B5D8 8003A9D8 0361D824 */  and        $k1, $k1, $at
    /* 3B5DC 8003A9DC 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 3B5E0 8003A9E0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 3B5E4 8003A9E4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 3B5E8 8003A9E8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 3B5EC 8003A9EC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 3B5F0 8003A9F0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 3B5F4 8003A9F4 03404025 */  or         $t0, $k0, $zero
    /* 3B5F8 8003A9F8 3C1A8005 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 3B5FC 8003A9FC 8F5AB580 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 3B600 8003AA00 DD090020 */  ld         $t1, 0x20($t0)
    /* 3B604 8003AA04 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 3B608 8003AA08 DD090118 */  ld         $t1, 0x118($t0)
    /* 3B60C 8003AA0C FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 3B610 8003AA10 DD090058 */  ld         $t1, 0x58($t0)
    /* 3B614 8003AA14 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 3B618 8003AA18 DD090060 */  ld         $t1, 0x60($t0)
    /* 3B61C 8003AA1C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 3B620 8003AA20 DD090068 */  ld         $t1, 0x68($t0)
    /* 3B624 8003AA24 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 3B628 8003AA28 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3B62C 8003AA2C 00004012 */  mflo       $t0
    /* 3B630 8003AA30 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 3B634 8003AA34 00004010 */  mfhi       $t0
    /* 3B638 8003AA38 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 3B63C 8003AA3C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 3B640 8003AA40 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 3B644 8003AA44 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 3B648 8003AA48 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 3B64C 8003AA4C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 3B650 8003AA50 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 3B654 8003AA54 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 3B658 8003AA58 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 3B65C 8003AA5C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 3B660 8003AA60 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 3B664 8003AA64 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 3B668 8003AA68 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 3B66C 8003AA6C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 3B670 8003AA70 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 3B674 8003AA74 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 3B678 8003AA78 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 3B67C 8003AA7C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 3B680 8003AA80 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 3B684 8003AA84 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 3B688 8003AA88 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 3B68C 8003AA8C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 3B690 8003AA90 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 3B694 8003AA94 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 3B698 8003AA98 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 3B69C 8003AA9C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 3B6A0 8003AAA0 11200011 */  beqz       $t1, .L8003AAE8
    /* 3B6A4 8003AAA4 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* 3B6A8 8003AAA8 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3B6AC 8003AAAC 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 3B6B0 8003AAB0 8D080000 */  lw         $t0, 0x0($t0)
    /* 3B6B4 8003AAB4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3B6B8 8003AAB8 01015026 */  xor        $t2, $t0, $at
    /* 3B6BC 8003AABC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 3B6C0 8003AAC0 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* 3B6C4 8003AAC4 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 3B6C8 8003AAC8 012A6025 */  or         $t4, $t1, $t2
    /* 3B6CC 8003AACC 03615824 */  and        $t3, $k1, $at
    /* 3B6D0 8003AAD0 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 3B6D4 8003AAD4 016C5825 */  or         $t3, $t3, $t4
    /* 3B6D8 8003AAD8 01284824 */  and        $t1, $t1, $t0
    /* 3B6DC 8003AADC 0361D824 */  and        $k1, $k1, $at
    /* 3B6E0 8003AAE0 AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* 3B6E4 8003AAE4 0369D825 */  or         $k1, $k1, $t1
  .L8003AAE8:
    /* 3B6E8 8003AAE8 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 3B6EC 8003AAEC 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 3B6F0 8003AAF0 1120000B */  beqz       $t1, .L8003AB20
    /* 3B6F4 8003AAF4 00000000 */   nop
    /* 3B6F8 8003AAF8 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3B6FC 8003AAFC 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 3B700 8003AB00 8D080000 */  lw         $t0, 0x0($t0)
    /* 3B704 8003AB04 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 3B708 8003AB08 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3B70C 8003AB0C 00084402 */  srl        $t0, $t0, 16
    /* 3B710 8003AB10 01014026 */  xor        $t0, $t0, $at
    /* 3B714 8003AB14 3108003F */  andi       $t0, $t0, 0x3F
    /* 3B718 8003AB18 010C4024 */  and        $t0, $t0, $t4
    /* 3B71C 8003AB1C 01284825 */  or         $t1, $t1, $t0
  .L8003AB20:
    /* 3B720 8003AB20 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 3B724 8003AB24 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 3B728 8003AB28 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 3B72C 8003AB2C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 3B730 8003AB30 11000014 */  beqz       $t0, .L8003AB84
    /* 3B734 8003AB34 00000000 */   nop
    /* 3B738 8003AB38 4448F800 */  cfc1       $t0, $31
    /* 3B73C 8003AB3C 00000000 */  nop
    /* 3B740 8003AB40 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 3B744 8003AB44 F7400130 */  sdc1       $f0, 0x130($k0)
    /* 3B748 8003AB48 F7420138 */  sdc1       $f2, 0x138($k0)
    /* 3B74C 8003AB4C F7440140 */  sdc1       $f4, 0x140($k0)
    /* 3B750 8003AB50 F7460148 */  sdc1       $f6, 0x148($k0)
    /* 3B754 8003AB54 F7480150 */  sdc1       $f8, 0x150($k0)
    /* 3B758 8003AB58 F74A0158 */  sdc1       $f10, 0x158($k0)
    /* 3B75C 8003AB5C F74C0160 */  sdc1       $f12, 0x160($k0)
    /* 3B760 8003AB60 F74E0168 */  sdc1       $f14, 0x168($k0)
    /* 3B764 8003AB64 F7500170 */  sdc1       $f16, 0x170($k0)
    /* 3B768 8003AB68 F7520178 */  sdc1       $f18, 0x178($k0)
    /* 3B76C 8003AB6C F7540180 */  sdc1       $f20, 0x180($k0)
    /* 3B770 8003AB70 F7560188 */  sdc1       $f22, 0x188($k0)
    /* 3B774 8003AB74 F7580190 */  sdc1       $f24, 0x190($k0)
    /* 3B778 8003AB78 F75A0198 */  sdc1       $f26, 0x198($k0)
    /* 3B77C 8003AB7C F75C01A0 */  sdc1       $f28, 0x1A0($k0)
    /* 3B780 8003AB80 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
  .L8003AB84:
    /* 3B784 8003AB84 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 3B788 8003AB88 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 3B78C 8003AB8C 24090002 */  addiu      $t1, $zero, 0x2
    /* 3B790 8003AB90 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 3B794 8003AB94 3109007C */  andi       $t1, $t0, 0x7C
    /* 3B798 8003AB98 240A0024 */  addiu      $t2, $zero, 0x24
    /* 3B79C 8003AB9C 112A00B0 */  beq        $t1, $t2, .L8003AE60
    /* 3B7A0 8003ABA0 00000000 */   nop
    /* 3B7A4 8003ABA4 240A002C */  addiu      $t2, $zero, 0x2C
    /* 3B7A8 8003ABA8 112A00FF */  beq        $t1, $t2, handle_CpU
    /* 3B7AC 8003ABAC 00000000 */   nop
    /* 3B7B0 8003ABB0 240A0000 */  addiu      $t2, $zero, 0x0
    /* 3B7B4 8003ABB4 152A00C3 */  bne        $t1, $t2, .L8003AEC4
    /* 3B7B8 8003ABB8 00000000 */   nop
    /* 3B7BC 8003ABBC 03688024 */  and        $s0, $k1, $t0
  .L8003ABC0:
    /* 3B7C0 8003ABC0 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 3B7C4 8003ABC4 00095302 */  srl        $t2, $t1, 12
    /* 3B7C8 8003ABC8 15400003 */  bnez       $t2, .L8003ABD8
    /* 3B7CC 8003ABCC 00000000 */   nop
    /* 3B7D0 8003ABD0 00095202 */  srl        $t2, $t1, 8
    /* 3B7D4 8003ABD4 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L8003ABD8:
    /* 3B7D8 8003ABD8 3C018005 */  lui        $at, %hi(D_8004C410)
    /* 3B7DC 8003ABDC 002A0821 */  addu       $at, $at, $t2
    /* 3B7E0 8003ABE0 902AC410 */  lbu        $t2, %lo(D_8004C410)($at)
    /* 3B7E4 8003ABE4 3C018005 */  lui        $at, %hi(jtbl_8004C430)
    /* 3B7E8 8003ABE8 002A0821 */  addu       $at, $at, $t2
    /* 3B7EC 8003ABEC 8C2AC430 */  lw         $t2, %lo(jtbl_8004C430)($at)
    /* 3B7F0 8003ABF0 01400008 */  jr         $t2
    /* 3B7F4 8003ABF4 00000000 */   nop
  jlabel .L8003ABF8
    /* 3B7F8 8003ABF8 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 3B7FC 8003ABFC 1000FFF0 */  b          .L8003ABC0
    /* 3B800 8003AC00 02018024 */   and       $s0, $s0, $at
  jlabel .L8003AC04
    /* 3B804 8003AC04 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 3B808 8003AC08 1000FFED */  b          .L8003ABC0
    /* 3B80C 8003AC0C 02018024 */   and       $s0, $s0, $at
  jlabel .L8003AC10
    /* 3B810 8003AC10 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 3B814 8003AC14 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 3B818 8003AC18 0C00EBBD */  jal        send_mesg
    /* 3B81C 8003AC1C 24040018 */   addiu     $a0, $zero, 0x18
    /* 3B820 8003AC20 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 3B824 8003AC24 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 3B828 8003AC28 1000FFE5 */  b          .L8003ABC0
    /* 3B82C 8003AC2C 02018024 */   and       $s0, $s0, $at
  jlabel .L8003AC30
    /* 3B830 8003AC30 2401F7FF */  addiu      $at, $zero, -0x801
    /* 3B834 8003AC34 02018024 */  and        $s0, $s0, $at
    /* 3B838 8003AC38 240A0004 */  addiu      $t2, $zero, 0x4
    /* 3B83C 8003AC3C 3C018005 */  lui        $at, %hi(__osHwIntTable)
    /* 3B840 8003AC40 002A0821 */  addu       $at, $at, $t2
    /* 3B844 8003AC44 8C2AB550 */  lw         $t2, %lo(__osHwIntTable)($at)
    /* 3B848 8003AC48 3C1D8006 */  lui        $sp, %hi(D_8005AAD0)
    /* 3B84C 8003AC4C 27BDAAD0 */  addiu      $sp, $sp, %lo(D_8005AAD0)
    /* 3B850 8003AC50 24040010 */  addiu      $a0, $zero, 0x10
    /* 3B854 8003AC54 11400007 */  beqz       $t2, .L8003AC74
    /* 3B858 8003AC58 27BD0FF0 */   addiu     $sp, $sp, 0xFF0
    /* 3B85C 8003AC5C 0140F809 */  jalr       $t2
    /* 3B860 8003AC60 00000000 */   nop
    /* 3B864 8003AC64 10400003 */  beqz       $v0, .L8003AC74
    /* 3B868 8003AC68 24040010 */   addiu     $a0, $zero, 0x10
    /* 3B86C 8003AC6C 10000082 */  b          .L8003AE78
    /* 3B870 8003AC70 00000000 */   nop
  .L8003AC74:
    /* 3B874 8003AC74 0C00EBBD */  jal        send_mesg
    /* 3B878 8003AC78 00000000 */   nop
    /* 3B87C 8003AC7C 1000FFD0 */  b          .L8003ABC0
    /* 3B880 8003AC80 00000000 */   nop
  jlabel .L8003AC84
    /* 3B884 8003AC84 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3B888 8003AC88 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 3B88C 8003AC8C 8D080000 */  lw         $t0, 0x0($t0)
    /* 3B890 8003AC90 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* 3B894 8003AC94 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* 3B898 8003AC98 00084402 */  srl        $t0, $t0, 16
    /* 3B89C 8003AC9C 02288824 */  and        $s1, $s1, $t0
    /* 3B8A0 8003ACA0 32290001 */  andi       $t1, $s1, 0x1
    /* 3B8A4 8003ACA4 11200013 */  beqz       $t1, .L8003ACF4
    /* 3B8A8 8003ACA8 00000000 */   nop
    /* 3B8AC 8003ACAC 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* 3B8B0 8003ACB0 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* 3B8B4 8003ACB4 24090008 */  addiu      $t1, $zero, 0x8
    /* 3B8B8 8003ACB8 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* 3B8BC 8003ACBC 318C0300 */  andi       $t4, $t4, 0x300
    /* 3B8C0 8003ACC0 3231003E */  andi       $s1, $s1, 0x3E
    /* 3B8C4 8003ACC4 11800007 */  beqz       $t4, .L8003ACE4
    /* 3B8C8 8003ACC8 AC290010 */   sw        $t1, %lo(D_A4040010)($at)
    /* 3B8CC 8003ACCC 0C00EBBD */  jal        send_mesg
    /* 3B8D0 8003ACD0 24040020 */   addiu     $a0, $zero, 0x20
    /* 3B8D4 8003ACD4 12200038 */  beqz       $s1, .L8003ADB8
    /* 3B8D8 8003ACD8 00000000 */   nop
    /* 3B8DC 8003ACDC 10000005 */  b          .L8003ACF4
    /* 3B8E0 8003ACE0 00000000 */   nop
  .L8003ACE4:
    /* 3B8E4 8003ACE4 0C00EBBD */  jal        send_mesg
    /* 3B8E8 8003ACE8 24040058 */   addiu     $a0, $zero, 0x58
    /* 3B8EC 8003ACEC 12200032 */  beqz       $s1, .L8003ADB8
    /* 3B8F0 8003ACF0 00000000 */   nop
  .L8003ACF4:
    /* 3B8F4 8003ACF4 32290008 */  andi       $t1, $s1, 0x8
    /* 3B8F8 8003ACF8 11200007 */  beqz       $t1, .L8003AD18
    /* 3B8FC 8003ACFC 3C01A440 */   lui       $at, %hi(D_A4400010)
    /* 3B900 8003AD00 32310037 */  andi       $s1, $s1, 0x37
    /* 3B904 8003AD04 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* 3B908 8003AD08 0C00EBBD */  jal        send_mesg
    /* 3B90C 8003AD0C 24040038 */   addiu     $a0, $zero, 0x38
    /* 3B910 8003AD10 12200029 */  beqz       $s1, .L8003ADB8
    /* 3B914 8003AD14 00000000 */   nop
  .L8003AD18:
    /* 3B918 8003AD18 32290004 */  andi       $t1, $s1, 0x4
    /* 3B91C 8003AD1C 11200009 */  beqz       $t1, .L8003AD44
    /* 3B920 8003AD20 00000000 */   nop
    /* 3B924 8003AD24 24090001 */  addiu      $t1, $zero, 0x1
    /* 3B928 8003AD28 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* 3B92C 8003AD2C 3231003B */  andi       $s1, $s1, 0x3B
    /* 3B930 8003AD30 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* 3B934 8003AD34 0C00EBBD */  jal        send_mesg
    /* 3B938 8003AD38 24040030 */   addiu     $a0, $zero, 0x30
    /* 3B93C 8003AD3C 1220001E */  beqz       $s1, .L8003ADB8
    /* 3B940 8003AD40 00000000 */   nop
  .L8003AD44:
    /* 3B944 8003AD44 32290002 */  andi       $t1, $s1, 0x2
    /* 3B948 8003AD48 11200007 */  beqz       $t1, .L8003AD68
    /* 3B94C 8003AD4C 3C01A480 */   lui       $at, %hi(D_A4800018)
    /* 3B950 8003AD50 3231003D */  andi       $s1, $s1, 0x3D
    /* 3B954 8003AD54 AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* 3B958 8003AD58 0C00EBBD */  jal        send_mesg
    /* 3B95C 8003AD5C 24040028 */   addiu     $a0, $zero, 0x28
    /* 3B960 8003AD60 12200015 */  beqz       $s1, .L8003ADB8
    /* 3B964 8003AD64 00000000 */   nop
  .L8003AD68:
    /* 3B968 8003AD68 32290010 */  andi       $t1, $s1, 0x10
    /* 3B96C 8003AD6C 11200009 */  beqz       $t1, .L8003AD94
    /* 3B970 8003AD70 00000000 */   nop
    /* 3B974 8003AD74 24090002 */  addiu      $t1, $zero, 0x2
    /* 3B978 8003AD78 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* 3B97C 8003AD7C 3231002F */  andi       $s1, $s1, 0x2F
    /* 3B980 8003AD80 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* 3B984 8003AD84 0C00EBBD */  jal        send_mesg
    /* 3B988 8003AD88 24040040 */   addiu     $a0, $zero, 0x40
    /* 3B98C 8003AD8C 1220000A */  beqz       $s1, .L8003ADB8
    /* 3B990 8003AD90 00000000 */   nop
  .L8003AD94:
    /* 3B994 8003AD94 32290020 */  andi       $t1, $s1, 0x20
    /* 3B998 8003AD98 11200007 */  beqz       $t1, .L8003ADB8
    /* 3B99C 8003AD9C 00000000 */   nop
    /* 3B9A0 8003ADA0 24090800 */  addiu      $t1, $zero, 0x800
    /* 3B9A4 8003ADA4 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* 3B9A8 8003ADA8 3231001F */  andi       $s1, $s1, 0x1F
    /* 3B9AC 8003ADAC AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* 3B9B0 8003ADB0 0C00EBBD */  jal        send_mesg
    /* 3B9B4 8003ADB4 24040048 */   addiu     $a0, $zero, 0x48
  .L8003ADB8:
    /* 3B9B8 8003ADB8 2401FBFF */  addiu      $at, $zero, -0x401
    /* 3B9BC 8003ADBC 1000FF80 */  b          .L8003ABC0
    /* 3B9C0 8003ADC0 02018024 */   and       $s0, $s0, $at
  jlabel .L8003ADC4
    /* 3B9C4 8003ADC4 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3B9C8 8003ADC8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 3B9CC 8003ADCC 3C098005 */  lui        $t1, %hi(osViClock + 0x4)
    /* 3B9D0 8003ADD0 0361D824 */  and        $k1, $k1, $at
    /* 3B9D4 8003ADD4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3B9D8 8003ADD8 2529B49C */  addiu      $t1, $t1, %lo(osViClock + 0x4)
    /* 3B9DC 8003ADDC 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 3B9E0 8003ADE0 11400003 */  beqz       $t2, .L8003ADF0
    /* 3B9E4 8003ADE4 2401EFFF */   addiu     $at, $zero, -0x1001
    /* 3B9E8 8003ADE8 10000023 */  b          .L8003AE78
    /* 3B9EC 8003ADEC 02018024 */   and       $s0, $s0, $at
  .L8003ADF0:
    /* 3B9F0 8003ADF0 240A0001 */  addiu      $t2, $zero, 0x1
    /* 3B9F4 8003ADF4 AD2A0000 */  sw         $t2, 0x0($t1)
    /* 3B9F8 8003ADF8 0C00EBBD */  jal        send_mesg
    /* 3B9FC 8003ADFC 24040070 */   addiu     $a0, $zero, 0x70
    /* 3BA00 8003AE00 3C0A8005 */  lui        $t2, %hi(__osRunQueue)
    /* 3BA04 8003AE04 8D4AB578 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 3BA08 8003AE08 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 3BA0C 8003AE0C 02018024 */  and        $s0, $s0, $at
    /* 3BA10 8003AE10 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 3BA14 8003AE14 0361D824 */  and        $k1, $k1, $at
    /* 3BA18 8003AE18 10000017 */  b          .L8003AE78
    /* 3BA1C 8003AE1C AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .L8003AE20
    /* 3BA20 8003AE20 2401FDFF */  addiu      $at, $zero, -0x201
    /* 3BA24 8003AE24 01014024 */  and        $t0, $t0, $at
    /* 3BA28 8003AE28 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 3BA2C 8003AE2C 0C00EBBD */  jal        send_mesg
    /* 3BA30 8003AE30 24040008 */   addiu     $a0, $zero, 0x8
    /* 3BA34 8003AE34 2401FDFF */  addiu      $at, $zero, -0x201
    /* 3BA38 8003AE38 1000FF61 */  b          .L8003ABC0
    /* 3BA3C 8003AE3C 02018024 */   and       $s0, $s0, $at
  jlabel .L8003AE40
    /* 3BA40 8003AE40 2401FEFF */  addiu      $at, $zero, -0x101
    /* 3BA44 8003AE44 01014024 */  and        $t0, $t0, $at
    /* 3BA48 8003AE48 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 3BA4C 8003AE4C 0C00EBBD */  jal        send_mesg
    /* 3BA50 8003AE50 24040000 */   addiu     $a0, $zero, 0x0
    /* 3BA54 8003AE54 2401FEFF */  addiu      $at, $zero, -0x101
    /* 3BA58 8003AE58 1000FF59 */  b          .L8003ABC0
    /* 3BA5C 8003AE5C 02018024 */   and       $s0, $s0, $at
  .L8003AE60:
    /* 3BA60 8003AE60 24090001 */  addiu      $t1, $zero, 0x1
    /* 3BA64 8003AE64 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 3BA68 8003AE68 0C00EBBD */  jal        send_mesg
    /* 3BA6C 8003AE6C 24040050 */   addiu     $a0, $zero, 0x50
    /* 3BA70 8003AE70 10000001 */  b          .L8003AE78
    /* 3BA74 8003AE74 00000000 */   nop
  jlabel .L8003AE78
    /* 3BA78 8003AE78 3C0A8005 */  lui        $t2, %hi(__osRunQueue)
    /* 3BA7C 8003AE7C 8D4AB578 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 3BA80 8003AE80 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 3BA84 8003AE84 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 3BA88 8003AE88 012B082A */  slt        $at, $t1, $t3
    /* 3BA8C 8003AE8C 10200007 */  beqz       $at, .L8003AEAC
    /* 3BA90 8003AE90 00000000 */   nop
    /* 3BA94 8003AE94 3C048005 */  lui        $a0, %hi(__osRunQueue)
    /* 3BA98 8003AE98 03402825 */  or         $a1, $k0, $zero
    /* 3BA9C 8003AE9C 0C00EC37 */  jal        __osEnqueueThread
    /* 3BAA0 8003AEA0 2484B578 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 3BAA4 8003AEA4 0800EC4D */  j          __osDispatchThread
    /* 3BAA8 8003AEA8 00000000 */   nop
  .L8003AEAC:
    /* 3BAAC 8003AEAC 3C098005 */  lui        $t1, %hi(__osRunQueue)
    /* 3BAB0 8003AEB0 2529B578 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* 3BAB4 8003AEB4 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 3BAB8 8003AEB8 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 3BABC 8003AEBC 0800EC4D */  j          __osDispatchThread
    /* 3BAC0 8003AEC0 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L8003AEC4:
    /* 3BAC4 8003AEC4 3C018005 */  lui        $at, %hi(__osFaultedThread)
    /* 3BAC8 8003AEC8 AC3AB584 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* 3BACC 8003AECC 24090001 */  addiu      $t1, $zero, 0x1
    /* 3BAD0 8003AED0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 3BAD4 8003AED4 24090002 */  addiu      $t1, $zero, 0x2
    /* 3BAD8 8003AED8 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 3BADC 8003AEDC 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 3BAE0 8003AEE0 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 3BAE4 8003AEE4 0C00EBBD */  jal        send_mesg
    /* 3BAE8 8003AEE8 24040060 */   addiu     $a0, $zero, 0x60
    /* 3BAEC 8003AEEC 0800EC4D */  j          __osDispatchThread
    /* 3BAF0 8003AEF0 00000000 */   nop
endlabel __osException

nonmatching send_mesg, 0xB4

glabel send_mesg
    /* 3BAF4 8003AEF4 3C0A8006 */  lui        $t2, %hi(__osEventStateTab)
    /* 3BAF8 8003AEF8 254AA380 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* 3BAFC 8003AEFC 01445021 */  addu       $t2, $t2, $a0
    /* 3BB00 8003AF00 8D490000 */  lw         $t1, 0x0($t2)
    /* 3BB04 8003AF04 03E09025 */  or         $s2, $ra, $zero
    /* 3BB08 8003AF08 11200025 */  beqz       $t1, .L8003AFA0
    /* 3BB0C 8003AF0C 00000000 */   nop
    /* 3BB10 8003AF10 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 3BB14 8003AF14 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 3BB18 8003AF18 016C082A */  slt        $at, $t3, $t4
    /* 3BB1C 8003AF1C 10200020 */  beqz       $at, .L8003AFA0
    /* 3BB20 8003AF20 00000000 */   nop
    /* 3BB24 8003AF24 8D2D000C */  lw         $t5, 0xC($t1)
    /* 3BB28 8003AF28 01AB6821 */  addu       $t5, $t5, $t3
    /* 3BB2C 8003AF2C 01AC001A */  div        $zero, $t5, $t4
    /* 3BB30 8003AF30 15800002 */  bnez       $t4, .L8003AF3C
    /* 3BB34 8003AF34 00000000 */   nop
    /* 3BB38 8003AF38 0007000D */  break      7
  .L8003AF3C:
    /* 3BB3C 8003AF3C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3BB40 8003AF40 15810004 */  bne        $t4, $at, .L8003AF54
    /* 3BB44 8003AF44 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 3BB48 8003AF48 15A10002 */  bne        $t5, $at, .L8003AF54
    /* 3BB4C 8003AF4C 00000000 */   nop
    /* 3BB50 8003AF50 0006000D */  break      6
  .L8003AF54:
    /* 3BB54 8003AF54 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 3BB58 8003AF58 00006810 */  mfhi       $t5
    /* 3BB5C 8003AF5C 000D6880 */  sll        $t5, $t5, 2
    /* 3BB60 8003AF60 018D6021 */  addu       $t4, $t4, $t5
    /* 3BB64 8003AF64 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 3BB68 8003AF68 256A0001 */  addiu      $t2, $t3, 0x1
    /* 3BB6C 8003AF6C AD8D0000 */  sw         $t5, 0x0($t4)
    /* 3BB70 8003AF70 AD2A0008 */  sw         $t2, 0x8($t1)
    /* 3BB74 8003AF74 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 3BB78 8003AF78 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 3BB7C 8003AF7C 11600008 */  beqz       $t3, .L8003AFA0
    /* 3BB80 8003AF80 00000000 */   nop
    /* 3BB84 8003AF84 0C00EC49 */  jal        __osPopThread
    /* 3BB88 8003AF88 01202025 */   or        $a0, $t1, $zero
    /* 3BB8C 8003AF8C 00405025 */  or         $t2, $v0, $zero
    /* 3BB90 8003AF90 3C048005 */  lui        $a0, %hi(__osRunQueue)
    /* 3BB94 8003AF94 01402825 */  or         $a1, $t2, $zero
    /* 3BB98 8003AF98 0C00EC37 */  jal        __osEnqueueThread
    /* 3BB9C 8003AF9C 2484B578 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L8003AFA0:
    /* 3BBA0 8003AFA0 02400008 */  jr         $s2
    /* 3BBA4 8003AFA4 00000000 */   nop
endlabel send_mesg

/* Handwritten function */
nonmatching handle_CpU, 0x34

glabel handle_CpU
    /* 3BBA8 8003AFA8 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 3BBAC 8003AFAC 01014824 */  and        $t1, $t0, $at
    /* 3BBB0 8003AFB0 00094F02 */  srl        $t1, $t1, 28
    /* 3BBB4 8003AFB4 240A0001 */  addiu      $t2, $zero, 0x1
    /* 3BBB8 8003AFB8 152AFFC2 */  bne        $t1, $t2, .L8003AEC4
    /* 3BBBC 8003AFBC 00000000 */   nop
    /* 3BBC0 8003AFC0 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3BBC4 8003AFC4 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 3BBC8 8003AFC8 24090001 */  addiu      $t1, $zero, 0x1
    /* 3BBCC 8003AFCC 0361D825 */  or         $k1, $k1, $at
    /* 3BBD0 8003AFD0 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 3BBD4 8003AFD4 1000FFB5 */  b          .L8003AEAC
    /* 3BBD8 8003AFD8 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
endlabel handle_CpU

/* Handwritten function */
nonmatching __osEnqueueAndYield, 0x100

glabel __osEnqueueAndYield
    /* 3BBDC 8003AFDC 3C058005 */  lui        $a1, %hi(__osRunningThread)
    /* 3BBE0 8003AFE0 8CA5B580 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 3BBE4 8003AFE4 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 3BBE8 8003AFE8 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 3BBEC 8003AFEC 35080002 */  ori        $t0, $t0, 0x2
    /* 3BBF0 8003AFF0 ACA80118 */  sw         $t0, 0x118($a1)
    /* 3BBF4 8003AFF4 FCB00098 */  sd         $s0, 0x98($a1)
    /* 3BBF8 8003AFF8 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 3BBFC 8003AFFC FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 3BC00 8003B000 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 3BC04 8003B004 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 3BC08 8003B008 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 3BC0C 8003B00C FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 3BC10 8003B010 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 3BC14 8003B014 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 3BC18 8003B018 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 3BC1C 8003B01C FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 3BC20 8003B020 FCBF0100 */  sd         $ra, 0x100($a1)
    /* 3BC24 8003B024 13600009 */  beqz       $k1, .L8003B04C /* handwritten instruction */
    /* 3BC28 8003B028 ACBF011C */   sw        $ra, 0x11C($a1)
    /* 3BC2C 8003B02C 445BF800 */  cfc1       $k1, $31
    /* 3BC30 8003B030 F4B40180 */  sdc1       $f20, 0x180($a1)
    /* 3BC34 8003B034 F4B60188 */  sdc1       $f22, 0x188($a1)
    /* 3BC38 8003B038 F4B80190 */  sdc1       $f24, 0x190($a1)
    /* 3BC3C 8003B03C F4BA0198 */  sdc1       $f26, 0x198($a1)
    /* 3BC40 8003B040 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
    /* 3BC44 8003B044 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
    /* 3BC48 8003B048 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L8003B04C:
    /* 3BC4C 8003B04C 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* 3BC50 8003B050 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 3BC54 8003B054 1120000D */  beqz       $t1, .L8003B08C
    /* 3BC58 8003B058 00000000 */   nop
    /* 3BC5C 8003B05C 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3BC60 8003B060 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 3BC64 8003B064 8D080000 */  lw         $t0, 0x0($t0)
    /* 3BC68 8003B068 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3BC6C 8003B06C 01014026 */  xor        $t0, $t0, $at
    /* 3BC70 8003B070 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 3BC74 8003B074 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 3BC78 8003B078 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 3BC7C 8003B07C 01284825 */  or         $t1, $t1, $t0
    /* 3BC80 8003B080 0361D824 */  and        $k1, $k1, $at
    /* 3BC84 8003B084 0369D825 */  or         $k1, $k1, $t1
    /* 3BC88 8003B088 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L8003B08C:
    /* 3BC8C 8003B08C 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* 3BC90 8003B090 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* 3BC94 8003B094 1360000B */  beqz       $k1, .L8003B0C4 /* handwritten instruction */
    /* 3BC98 8003B098 00000000 */   nop
    /* 3BC9C 8003B09C 3C1A8005 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 3BCA0 8003B0A0 275AB4A0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 3BCA4 8003B0A4 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 3BCA8 8003B0A8 8CA80128 */  lw         $t0, 0x128($a1)
    /* 3BCAC 8003B0AC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 3BCB0 8003B0B0 001AD402 */  srl        $k0, $k0, 16
    /* 3BCB4 8003B0B4 0341D026 */  xor        $k0, $k0, $at
    /* 3BCB8 8003B0B8 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* 3BCBC 8003B0BC 0348D024 */  and        $k0, $k0, $t0
    /* 3BCC0 8003B0C0 037AD825 */  or         $k1, $k1, $k0
  .L8003B0C4:
    /* 3BCC4 8003B0C4 10800003 */  beqz       $a0, .L8003B0D4
    /* 3BCC8 8003B0C8 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 3BCCC 8003B0CC 0C00EC37 */  jal        __osEnqueueThread
    /* 3BCD0 8003B0D0 00000000 */   nop
  .L8003B0D4:
    /* 3BCD4 8003B0D4 0800EC4D */  j          __osDispatchThread
    /* 3BCD8 8003B0D8 00000000 */   nop
endlabel __osEnqueueAndYield

nonmatching __osEnqueueThread, 0x48

glabel __osEnqueueThread
    /* 3BCDC 8003B0DC 8C980000 */  lw         $t8, 0x0($a0)
    /* 3BCE0 8003B0E0 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 3BCE4 8003B0E4 0080C825 */  or         $t9, $a0, $zero
    /* 3BCE8 8003B0E8 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 3BCEC 8003B0EC 01CF082A */  slt        $at, $t6, $t7
    /* 3BCF0 8003B0F0 14200007 */  bnez       $at, .L8003B110
    /* 3BCF4 8003B0F4 00000000 */   nop
  .L8003B0F8:
    /* 3BCF8 8003B0F8 0300C825 */  or         $t9, $t8, $zero
    /* 3BCFC 8003B0FC 8F180000 */  lw         $t8, 0x0($t8)
    /* 3BD00 8003B100 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 3BD04 8003B104 01CF082A */  slt        $at, $t6, $t7
    /* 3BD08 8003B108 1020FFFB */  beqz       $at, .L8003B0F8
    /* 3BD0C 8003B10C 00000000 */   nop
  .L8003B110:
    /* 3BD10 8003B110 8F380000 */  lw         $t8, 0x0($t9)
    /* 3BD14 8003B114 ACB80000 */  sw         $t8, 0x0($a1)
    /* 3BD18 8003B118 AF250000 */  sw         $a1, 0x0($t9)
    /* 3BD1C 8003B11C 03E00008 */  jr         $ra
    /* 3BD20 8003B120 ACA40008 */   sw        $a0, 0x8($a1)
endlabel __osEnqueueThread

nonmatching __osPopThread, 0x10

glabel __osPopThread
    /* 3BD24 8003B124 8C820000 */  lw         $v0, 0x0($a0)
    /* 3BD28 8003B128 8C590000 */  lw         $t9, 0x0($v0)
    /* 3BD2C 8003B12C 03E00008 */  jr         $ra
    /* 3BD30 8003B130 AC990000 */   sw        $t9, 0x0($a0)
endlabel __osPopThread

/* Handwritten function */
nonmatching __osDispatchThread, 0x17C

glabel __osDispatchThread
    /* 3BD34 8003B134 3C048005 */  lui        $a0, %hi(__osRunQueue)
    /* 3BD38 8003B138 0C00EC49 */  jal        __osPopThread
    /* 3BD3C 8003B13C 2484B578 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 3BD40 8003B140 3C018005 */  lui        $at, %hi(__osRunningThread)
    /* 3BD44 8003B144 AC22B580 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 3BD48 8003B148 24080004 */  addiu      $t0, $zero, 0x4
    /* 3BD4C 8003B14C A4480010 */  sh         $t0, 0x10($v0)
    /* 3BD50 8003B150 0040D025 */  or         $k0, $v0, $zero
    /* 3BD54 8003B154 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3BD58 8003B158 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3BD5C 8003B15C 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 3BD60 8003B160 8D080000 */  lw         $t0, 0x0($t0)
    /* 3BD64 8003B164 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 3BD68 8003B168 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 3BD6C 8003B16C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 3BD70 8003B170 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 3BD74 8003B174 01284824 */  and        $t1, $t1, $t0
    /* 3BD78 8003B178 0361D824 */  and        $k1, $k1, $at
    /* 3BD7C 8003B17C 0369D825 */  or         $k1, $k1, $t1
    /* 3BD80 8003B180 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 3BD84 8003B184 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 3BD88 8003B188 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 3BD8C 8003B18C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 3BD90 8003B190 03600013 */  mtlo       $k1
    /* 3BD94 8003B194 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 3BD98 8003B198 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 3BD9C 8003B19C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 3BDA0 8003B1A0 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 3BDA4 8003B1A4 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 3BDA8 8003B1A8 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 3BDAC 8003B1AC DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 3BDB0 8003B1B0 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 3BDB4 8003B1B4 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 3BDB8 8003B1B8 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 3BDBC 8003B1BC DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 3BDC0 8003B1C0 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 3BDC4 8003B1C4 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 3BDC8 8003B1C8 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 3BDCC 8003B1CC DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 3BDD0 8003B1D0 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 3BDD4 8003B1D4 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 3BDD8 8003B1D8 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 3BDDC 8003B1DC DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 3BDE0 8003B1E0 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 3BDE4 8003B1E4 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 3BDE8 8003B1E8 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 3BDEC 8003B1EC DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 3BDF0 8003B1F0 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 3BDF4 8003B1F4 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 3BDF8 8003B1F8 03600011 */  mthi       $k1
    /* 3BDFC 8003B1FC DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 3BE00 8003B200 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 3BE04 8003B204 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 3BE08 8003B208 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 3BE0C 8003B20C 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 3BE10 8003B210 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 3BE14 8003B214 13600013 */  beqz       $k1, .L8003B264 /* handwritten instruction */
    /* 3BE18 8003B218 00000000 */   nop
    /* 3BE1C 8003B21C 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 3BE20 8003B220 44DBF800 */  ctc1       $k1, $31
    /* 3BE24 8003B224 D7400130 */  ldc1       $f0, 0x130($k0)
    /* 3BE28 8003B228 D7420138 */  ldc1       $f2, 0x138($k0)
    /* 3BE2C 8003B22C D7440140 */  ldc1       $f4, 0x140($k0)
    /* 3BE30 8003B230 D7460148 */  ldc1       $f6, 0x148($k0)
    /* 3BE34 8003B234 D7480150 */  ldc1       $f8, 0x150($k0)
    /* 3BE38 8003B238 D74A0158 */  ldc1       $f10, 0x158($k0)
    /* 3BE3C 8003B23C D74C0160 */  ldc1       $f12, 0x160($k0)
    /* 3BE40 8003B240 D74E0168 */  ldc1       $f14, 0x168($k0)
    /* 3BE44 8003B244 D7500170 */  ldc1       $f16, 0x170($k0)
    /* 3BE48 8003B248 D7520178 */  ldc1       $f18, 0x178($k0)
    /* 3BE4C 8003B24C D7540180 */  ldc1       $f20, 0x180($k0)
    /* 3BE50 8003B250 D7560188 */  ldc1       $f22, 0x188($k0)
    /* 3BE54 8003B254 D7580190 */  ldc1       $f24, 0x190($k0)
    /* 3BE58 8003B258 D75A0198 */  ldc1       $f26, 0x198($k0)
    /* 3BE5C 8003B25C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
    /* 3BE60 8003B260 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
  .L8003B264:
    /* 3BE64 8003B264 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 3BE68 8003B268 3C1A8005 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 3BE6C 8003B26C 275AB4A0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 3BE70 8003B270 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 3BE74 8003B274 001AD402 */  srl        $k0, $k0, 16
    /* 3BE78 8003B278 037AD824 */  and        $k1, $k1, $k0
    /* 3BE7C 8003B27C 001BD840 */  sll        $k1, $k1, 1
    /* 3BE80 8003B280 3C1A8005 */  lui        $k0, %hi(D_8004C010) /* handwritten instruction */
    /* 3BE84 8003B284 275AC010 */  addiu      $k0, $k0, %lo(D_8004C010) /* handwritten instruction */
    /* 3BE88 8003B288 037AD821 */  addu       $k1, $k1, $k0
    /* 3BE8C 8003B28C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 3BE90 8003B290 3C1AA430 */  lui        $k0, %hi(D_A430000C) /* handwritten instruction */
    /* 3BE94 8003B294 275A000C */  addiu      $k0, $k0, %lo(D_A430000C) /* handwritten instruction */
    /* 3BE98 8003B298 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 3BE9C 8003B29C 00000000 */  nop
    /* 3BEA0 8003B2A0 00000000 */  nop
    /* 3BEA4 8003B2A4 00000000 */  nop
    /* 3BEA8 8003B2A8 00000000 */  nop
    /* 3BEAC 8003B2AC 42000018 */  eret /* handwritten instruction */
endlabel __osDispatchThread

nonmatching __osCleanupThread, 0x8

glabel __osCleanupThread
    /* 3BEB0 8003B2B0 0C0116A8 */  jal        osDestroyThread
    /* 3BEB4 8003B2B4 00002025 */   or        $a0, $zero, $zero
endlabel __osCleanupThread
    /* 3BEB8 8003B2B8 00000000 */  nop
    /* 3BEBC 8003B2BC 00000000 */  nop
