.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osGetCount, 0xC

glabel osGetCount
    /* 3D540 8003C940 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 3D544 8003C944 03E00008 */  jr         $ra
    /* 3D548 8003C948 00000000 */   nop
endlabel osGetCount
    /* 3D54C 8003C94C 00000000 */  nop
