.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osGetSR, 0xC

glabel __osGetSR
    /* 3B4F0 8003A8F0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 3B4F4 8003A8F4 03E00008 */  jr         $ra
    /* 3B4F8 8003A8F8 00000000 */   nop
endlabel __osGetSR
    /* 3B4FC 8003A8FC 00000000 */  nop
