.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osDisableInt, 0x20

glabel __osDisableInt
    /* 3C020 8003B420 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 3C024 8003B424 2401FFFE */  addiu      $at, $zero, -0x2
    /* 3C028 8003B428 01014824 */  and        $t1, $t0, $at
    /* 3C02C 8003B42C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 3C030 8003B430 31020001 */  andi       $v0, $t0, 0x1
    /* 3C034 8003B434 00000000 */  nop
    /* 3C038 8003B438 03E00008 */  jr         $ra
    /* 3C03C 8003B43C 00000000 */   nop
endlabel __osDisableInt

/* Handwritten function */
nonmatching __osRestoreInt, 0x1C

glabel __osRestoreInt
    /* 3C040 8003B440 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 3C044 8003B444 01044025 */  or         $t0, $t0, $a0
    /* 3C048 8003B448 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 3C04C 8003B44C 00000000 */  nop
    /* 3C050 8003B450 00000000 */  nop
    /* 3C054 8003B454 03E00008 */  jr         $ra
    /* 3C058 8003B458 00000000 */   nop
endlabel __osRestoreInt
    /* 3C05C 8003B45C 00000000 */  nop
