.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osInvalDCache, 0xAC

glabel osInvalDCache
    /* 322C0 800316C0 18A0001F */  blez       $a1, .L80031740
    /* 322C4 800316C4 00000000 */   nop
    /* 322C8 800316C8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 322CC 800316CC 00AB082B */  sltu       $at, $a1, $t3
    /* 322D0 800316D0 1020001D */  beqz       $at, .L80031748
    /* 322D4 800316D4 00000000 */   nop
    /* 322D8 800316D8 00804025 */  or         $t0, $a0, $zero
    /* 322DC 800316DC 00854821 */  addu       $t1, $a0, $a1
    /* 322E0 800316E0 0109082B */  sltu       $at, $t0, $t1
    /* 322E4 800316E4 10200016 */  beqz       $at, .L80031740
    /* 322E8 800316E8 00000000 */   nop
    /* 322EC 800316EC 310A000F */  andi       $t2, $t0, 0xF
    /* 322F0 800316F0 11400007 */  beqz       $t2, .L80031710
    /* 322F4 800316F4 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 322F8 800316F8 010A4023 */  subu       $t0, $t0, $t2
    /* 322FC 800316FC BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 32300 80031700 0109082B */  sltu       $at, $t0, $t1
    /* 32304 80031704 1020000E */  beqz       $at, .L80031740
    /* 32308 80031708 00000000 */   nop
    /* 3230C 8003170C 25080010 */  addiu      $t0, $t0, 0x10
  .L80031710:
    /* 32310 80031710 312A000F */  andi       $t2, $t1, 0xF
    /* 32314 80031714 11400006 */  beqz       $t2, .L80031730
    /* 32318 80031718 00000000 */   nop
    /* 3231C 8003171C 012A4823 */  subu       $t1, $t1, $t2
    /* 32320 80031720 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 32324 80031724 0128082B */  sltu       $at, $t1, $t0
    /* 32328 80031728 14200005 */  bnez       $at, .L80031740
    /* 3232C 8003172C 00000000 */   nop
  .L80031730:
    /* 32330 80031730 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 32334 80031734 0109082B */  sltu       $at, $t0, $t1
    /* 32338 80031738 1420FFFD */  bnez       $at, .L80031730
    /* 3233C 8003173C 25080010 */   addiu     $t0, $t0, 0x10
  .L80031740:
    /* 32340 80031740 03E00008 */  jr         $ra
    /* 32344 80031744 00000000 */   nop
  .L80031748:
    /* 32348 80031748 3C088000 */  lui        $t0, 0x8000
    /* 3234C 8003174C 010B4821 */  addu       $t1, $t0, $t3
    /* 32350 80031750 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80031754:
    /* 32354 80031754 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 32358 80031758 0109082B */  sltu       $at, $t0, $t1
    /* 3235C 8003175C 1420FFFD */  bnez       $at, .L80031754
    /* 32360 80031760 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 32364 80031764 03E00008 */  jr         $ra
    /* 32368 80031768 00000000 */   nop
endlabel osInvalDCache
    /* 3236C 8003176C 00000000 */  nop
