.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osInvalICache, 0x74

glabel osInvalICache
    /* 32240 80031640 18A00011 */  blez       $a1, .L80031688
    /* 32244 80031644 00000000 */   nop
    /* 32248 80031648 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 3224C 8003164C 00AB082B */  sltu       $at, $a1, $t3
    /* 32250 80031650 1020000F */  beqz       $at, .L80031690
    /* 32254 80031654 00000000 */   nop
    /* 32258 80031658 00804025 */  or         $t0, $a0, $zero
    /* 3225C 8003165C 00854821 */  addu       $t1, $a0, $a1
    /* 32260 80031660 0109082B */  sltu       $at, $t0, $t1
    /* 32264 80031664 10200008 */  beqz       $at, .L80031688
    /* 32268 80031668 00000000 */   nop
    /* 3226C 8003166C 310A001F */  andi       $t2, $t0, 0x1F
    /* 32270 80031670 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 32274 80031674 010A4023 */  subu       $t0, $t0, $t2
  .L80031678:
    /* 32278 80031678 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 3227C 8003167C 0109082B */  sltu       $at, $t0, $t1
    /* 32280 80031680 1420FFFD */  bnez       $at, .L80031678
    /* 32284 80031684 25080020 */   addiu     $t0, $t0, 0x20
  .L80031688:
    /* 32288 80031688 03E00008 */  jr         $ra
    /* 3228C 8003168C 00000000 */   nop
  .L80031690:
    /* 32290 80031690 3C088000 */  lui        $t0, 0x8000
    /* 32294 80031694 010B4821 */  addu       $t1, $t0, $t3
    /* 32298 80031698 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L8003169C:
    /* 3229C 8003169C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 322A0 800316A0 0109082B */  sltu       $at, $t0, $t1
    /* 322A4 800316A4 1420FFFD */  bnez       $at, .L8003169C
    /* 322A8 800316A8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 322AC 800316AC 03E00008 */  jr         $ra
    /* 322B0 800316B0 00000000 */   nop
endlabel osInvalICache
    /* 322B4 800316B4 00000000 */  nop
    /* 322B8 800316B8 00000000 */  nop
    /* 322BC 800316BC 00000000 */  nop
