.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osMapTLBRdb, 0x58

glabel osMapTLBRdb
    /* 3BEC0 8003B2C0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 3BEC4 8003B2C4 2409001F */  addiu      $t1, $zero, 0x1F
    /* 3BEC8 8003B2C8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 3BECC 8003B2CC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 3BED0 8003B2D0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 3BED4 8003B2D4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 3BED8 8003B2D8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 3BEDC 8003B2DC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 3BEE0 8003B2E0 00095982 */  srl        $t3, $t1, 6
    /* 3BEE4 8003B2E4 016A5825 */  or         $t3, $t3, $t2
    /* 3BEE8 8003B2E8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 3BEEC 8003B2EC 24090001 */  addiu      $t1, $zero, 0x1
    /* 3BEF0 8003B2F0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 3BEF4 8003B2F4 00000000 */  nop
    /* 3BEF8 8003B2F8 42000002 */  tlbwi /* handwritten instruction */
    /* 3BEFC 8003B2FC 00000000 */  nop
    /* 3BF00 8003B300 00000000 */  nop
    /* 3BF04 8003B304 00000000 */  nop
    /* 3BF08 8003B308 00000000 */  nop
    /* 3BF0C 8003B30C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 3BF10 8003B310 03E00008 */  jr         $ra
    /* 3BF14 8003B314 00000000 */   nop
endlabel osMapTLBRdb
    /* 3BF18 8003B318 00000000 */  nop
    /* 3BF1C 8003B31C 00000000 */  nop
