.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osProbeTLB, 0xB8

glabel __osProbeTLB
    /* 3FD80 8003F180 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 3FD84 8003F184 310900FF */  andi       $t1, $t0, 0xFF
    /* 3FD88 8003F188 2401E000 */  addiu      $at, $zero, -0x2000
    /* 3FD8C 8003F18C 00815024 */  and        $t2, $a0, $at
    /* 3FD90 8003F190 012A4825 */  or         $t1, $t1, $t2
    /* 3FD94 8003F194 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 3FD98 8003F198 00000000 */  nop
    /* 3FD9C 8003F19C 00000000 */  nop
    /* 3FDA0 8003F1A0 00000000 */  nop
    /* 3FDA4 8003F1A4 42000008 */  tlbp /* handwritten instruction */
    /* 3FDA8 8003F1A8 00000000 */  nop
    /* 3FDAC 8003F1AC 00000000 */  nop
    /* 3FDB0 8003F1B0 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 3FDB4 8003F1B4 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 3FDB8 8003F1B8 01615824 */  and        $t3, $t3, $at
    /* 3FDBC 8003F1BC 1560001A */  bnez       $t3, .L8003F228
    /* 3FDC0 8003F1C0 00000000 */   nop
    /* 3FDC4 8003F1C4 42000001 */  tlbr /* handwritten instruction */
    /* 3FDC8 8003F1C8 00000000 */  nop
    /* 3FDCC 8003F1CC 00000000 */  nop
    /* 3FDD0 8003F1D0 00000000 */  nop
    /* 3FDD4 8003F1D4 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 3FDD8 8003F1D8 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 3FDDC 8003F1DC 000B5842 */  srl        $t3, $t3, 1
    /* 3FDE0 8003F1E0 01646024 */  and        $t4, $t3, $a0
    /* 3FDE4 8003F1E4 15800004 */  bnez       $t4, .L8003F1F8
    /* 3FDE8 8003F1E8 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 3FDEC 8003F1EC 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 3FDF0 8003F1F0 10000002 */  b          .L8003F1FC
    /* 3FDF4 8003F1F4 00000000 */   nop
  .L8003F1F8:
    /* 3FDF8 8003F1F8 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L8003F1FC:
    /* 3FDFC 8003F1FC 304D0002 */  andi       $t5, $v0, 0x2
    /* 3FE00 8003F200 11A00009 */  beqz       $t5, .L8003F228
    /* 3FE04 8003F204 00000000 */   nop
    /* 3FE08 8003F208 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 3FE0C 8003F20C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 3FE10 8003F210 00411024 */  and        $v0, $v0, $at
    /* 3FE14 8003F214 00021180 */  sll        $v0, $v0, 6
    /* 3FE18 8003F218 008B6824 */  and        $t5, $a0, $t3
    /* 3FE1C 8003F21C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 3FE20 8003F220 10000002 */  b          .L8003F22C
    /* 3FE24 8003F224 00000000 */   nop
  .L8003F228:
    /* 3FE28 8003F228 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8003F22C:
    /* 3FE2C 8003F22C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 3FE30 8003F230 03E00008 */  jr         $ra
    /* 3FE34 8003F234 00000000 */   nop
endlabel __osProbeTLB
    /* 3FE38 8003F238 00000000 */  nop
    /* 3FE3C 8003F23C 00000000 */  nop
