.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osSetCompare, 0xC

glabel __osSetCompare
    /* 46940 80045D40 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 46944 80045D44 03E00008 */  jr         $ra
    /* 46948 80045D48 00000000 */   nop
endlabel __osSetCompare
    /* 4694C 80045D4C 00000000 */  nop
