.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching __osSetFpcCsr, 0x10

glabel __osSetFpcCsr
    /* 3B500 8003A900 4442F800 */  cfc1       $v0, $31
    /* 3B504 8003A904 44C4F800 */  ctc1       $a0, $31
    /* 3B508 8003A908 03E00008 */  jr         $ra
    /* 3B50C 8003A90C 00000000 */   nop
endlabel __osSetFpcCsr
