.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osSetIntMask, 0xA0

glabel osSetIntMask
    /* 32B70 80031F70 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* 32B74 80031F74 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* 32B78 80031F78 3C088005 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 32B7C 80031F7C 2508B4A0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 32B80 80031F80 8D0B0000 */  lw         $t3, 0x0($t0)
    /* 32B84 80031F84 2401FFFF */  addiu      $at, $zero, -0x1
    /* 32B88 80031F88 01614026 */  xor        $t0, $t3, $at
    /* 32B8C 80031F8C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 32B90 80031F90 00481025 */  or         $v0, $v0, $t0
    /* 32B94 80031F94 3C0AA430 */  lui        $t2, %hi(D_A430000C)
    /* 32B98 80031F98 8D4A000C */  lw         $t2, %lo(D_A430000C)($t2)
    /* 32B9C 80031F9C 11400005 */  beqz       $t2, .L80031FB4
    /* 32BA0 80031FA0 000B4C02 */   srl       $t1, $t3, 16
    /* 32BA4 80031FA4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 32BA8 80031FA8 01214826 */  xor        $t1, $t1, $at
    /* 32BAC 80031FAC 3129003F */  andi       $t1, $t1, 0x3F
    /* 32BB0 80031FB0 01495025 */  or         $t2, $t2, $t1
  .L80031FB4:
    /* 32BB4 80031FB4 000A5400 */  sll        $t2, $t2, 16
    /* 32BB8 80031FB8 004A1025 */  or         $v0, $v0, $t2
    /* 32BBC 80031FBC 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* 32BC0 80031FC0 00814024 */  and        $t0, $a0, $at
    /* 32BC4 80031FC4 010B4024 */  and        $t0, $t0, $t3
    /* 32BC8 80031FC8 000843C2 */  srl        $t0, $t0, 15
    /* 32BCC 80031FCC 3C0A8005 */  lui        $t2, %hi(D_8004C010)
    /* 32BD0 80031FD0 01485021 */  addu       $t2, $t2, $t0
    /* 32BD4 80031FD4 954AC010 */  lhu        $t2, %lo(D_8004C010)($t2)
    /* 32BD8 80031FD8 3C01A430 */  lui        $at, %hi(D_A430000C)
    /* 32BDC 80031FDC AC2A000C */  sw         $t2, %lo(D_A430000C)($at)
    /* 32BE0 80031FE0 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* 32BE4 80031FE4 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* 32BE8 80031FE8 01094024 */  and        $t0, $t0, $t1
    /* 32BEC 80031FEC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 32BF0 80031FF0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 32BF4 80031FF4 01816024 */  and        $t4, $t4, $at
    /* 32BF8 80031FF8 01886025 */  or         $t4, $t4, $t0
    /* 32BFC 80031FFC 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* 32C00 80032000 00000000 */  nop
    /* 32C04 80032004 00000000 */  nop
    /* 32C08 80032008 03E00008 */  jr         $ra
    /* 32C0C 8003200C 00000000 */   nop
endlabel osSetIntMask
