.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching __osSetSR, 0x10

glabel __osSetSR
    /* 3B4E0 8003A8E0 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 3B4E4 8003A8E4 00000000 */  nop
    /* 3B4E8 8003A8E8 03E00008 */  jr         $ra
    /* 3B4EC 8003A8EC 00000000 */   nop
endlabel __osSetSR
