.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osWritebackDCacheAll, 0x28

glabel osWritebackDCacheAll
    /* 32EB0 800322B0 3C088000 */  lui        $t0, 0x8000
    /* 32EB4 800322B4 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 32EB8 800322B8 010A4821 */  addu       $t1, $t0, $t2
    /* 32EBC 800322BC 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800322C0:
    /* 32EC0 800322C0 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 32EC4 800322C4 0109082B */  sltu       $at, $t0, $t1
    /* 32EC8 800322C8 1420FFFD */  bnez       $at, .L800322C0
    /* 32ECC 800322CC 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 32ED0 800322D0 03E00008 */  jr         $ra
    /* 32ED4 800322D4 00000000 */   nop
endlabel osWritebackDCacheAll
    /* 32ED8 800322D8 00000000 */  nop
    /* 32EDC 800322DC 00000000 */  nop
