.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osWritebackDCache, 0x74

glabel osWritebackDCache
    /* 321C0 800315C0 18A00011 */  blez       $a1, .L80031608
    /* 321C4 800315C4 00000000 */   nop
    /* 321C8 800315C8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 321CC 800315CC 00AB082B */  sltu       $at, $a1, $t3
    /* 321D0 800315D0 1020000F */  beqz       $at, .L80031610
    /* 321D4 800315D4 00000000 */   nop
    /* 321D8 800315D8 00804025 */  or         $t0, $a0, $zero
    /* 321DC 800315DC 00854821 */  addu       $t1, $a0, $a1
    /* 321E0 800315E0 0109082B */  sltu       $at, $t0, $t1
    /* 321E4 800315E4 10200008 */  beqz       $at, .L80031608
    /* 321E8 800315E8 00000000 */   nop
    /* 321EC 800315EC 310A000F */  andi       $t2, $t0, 0xF
    /* 321F0 800315F0 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 321F4 800315F4 010A4023 */  subu       $t0, $t0, $t2
  .L800315F8:
    /* 321F8 800315F8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 321FC 800315FC 0109082B */  sltu       $at, $t0, $t1
    /* 32200 80031600 1420FFFD */  bnez       $at, .L800315F8
    /* 32204 80031604 25080010 */   addiu     $t0, $t0, 0x10
  .L80031608:
    /* 32208 80031608 03E00008 */  jr         $ra
    /* 3220C 8003160C 00000000 */   nop
  .L80031610:
    /* 32210 80031610 3C088000 */  lui        $t0, 0x8000
    /* 32214 80031614 010B4821 */  addu       $t1, $t0, $t3
    /* 32218 80031618 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8003161C:
    /* 3221C 8003161C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 32220 80031620 0109082B */  sltu       $at, $t0, $t1
    /* 32224 80031624 1420FFFD */  bnez       $at, .L8003161C
    /* 32228 80031628 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 3222C 8003162C 03E00008 */  jr         $ra
    /* 32230 80031630 00000000 */   nop
endlabel osWritebackDCache
    /* 32234 80031634 00000000 */  nop
    /* 32238 80031638 00000000 */  nop
    /* 3223C 8003163C 00000000 */  nop
